### ISSUE TITLE
List comprehension: false claim

### ISSUE THREAD

**Issue by cc7768** [NYUDataBootcamp/Book#21]
In the list comprehension section, we have

> It's another thing that doesn't work in Python 2, so make sure you have Python 3 installed.

This is false. We should remove it.

**Comment by spencerlyon2** [comment]
I thought I had done that – guess not. Let’s get rid of it



// Spencer

On October 19, 2016 at 4:48:42 PM, Chase Coleman (notifications@github.com)
wrote:

In the list comprehension section, we have

It's another thing that doesn't work in Python 2, so make sure you have
Python 3 installed.

This is false. We should remove it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NYUDataBootcamp/Book/issues/21>, or mute the thread

**Comment by cc7768** [comment]
You did... I'm reading my old paper version of the book

Removed in commit https://github.com/NYUDataBootcamp/Book/commit/7935b6916c21ce4187be7cdc82ccb97cf335ea68
